sudo: required

services:
  - docker

language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

notifications:
  slack:
    rooms:
      - settlemint:5QuOPa3Z4kJbfbNIgei0asur#mint

node_js:
  - '9'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

script:
  - npm run build
  # - npm run test

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - bash ./scripts/deploy.sh
    on:
      all_branches: true
      repo: databrokerdao/website
